### ISSUE TITLE
Assign badge won't work.

### ISSUE THREAD

**Issue by Ailrun** [mpj/ffforumautomator#1]
Hi MPJ!
I watch your video and notice that there is a bug on your modified code.

https://github.com/mpj/ffforumautomator/blob/fe7cfc2b586559bf75b61eef107a1b1e6fb7fcf7/assignbadge.js#L12

`errorUnlessOk` takes one argument, `operationName` and then it returns a function appropriate to `then`.

You can check it in https://github.com/mpj/ffforumautomator/blob/fe7cfc2b586559bf75b61eef107a1b1e6fb7fcf7/error-unless-ok.js#L1

If you read issue, you can safely ignore my comment on the video (the one about this bug).

**Comment by mpj** [comment]
Ooopsie. It does actually still work in the happy path, but won't actually break on non-200.
Fixed in https://github.com/mpj/ffforumautomator/commit/02d1479d191dfc422fa60503b2ae839a1c9f30db

**Comment by Ailrun** [comment]
@mpj Thx!
